
#hey travis, I need sudo
sudo: required

#hey travis, I need docker
services:
  - docker

#hey travis, do this before trying to run scripts
before_install:
  - docker build -t peterk/docker-react -f Dockerfile.dev .

#scripts are run until we are done or hit an error
#travis expects the running command to exit (so cant just run npm run test)
script:
  - docker run peterk/docker-react npm run test -- --coverage
